version: "2"

services:
  config-server:
    build: microservices-config-server/.
    working_dir: /
    ports:
      - "8888:8888"
  eureka:
    build: microservices-eureka/.
    working_dir: /
    links:
      - config-server
    ports:
      - "8761:8761"
    command: ./wait-for-it.sh config-server:8888 -t 60 --
    command: java -Dspring.profiles.active=docker -jar /app.jar
  authserver:
    build: microservices-authserver/.
    working_dir: /
    links:
      - config-server
    ports:
      - "9999:9999"
    command: ./wait-for-it.sh config-server:8888 -t 60 --
    command: java -Dspring.profiles.active=docker -jar /app.jar
  hystrix:
    build: microservices-hystrix-dashboard/.
    working_dir: /
    ports:
      - "7979:7979"
    command: ./wait-for-it.sh config-server:8888 -t 60 --
    command: java -Dspring.profiles.active=docker -jar /app.jar
  employee:
    build: microservices-employee/.
    working_dir: /
    links:
      - config-server
      - authserver
      - eureka
    ports:
      - "8082:8082"
    command: ./wait-for-it.sh config-server:8888 -t 60 --
    command: java -Dspring.profiles.active=docker -jar /app.jar
  organization:
    build: microservices-organization/.
    working_dir: /
    links:
      - config-server
      - authserver
      - eureka
    ports:
      - "8083:8083"
    command: ./wait-for-it.sh config-server:8888 -t 60 --
    command: java -Dspring.profiles.active=docker -jar /app.jar
  department:
    build: microservices-department/.
    working_dir: /
    links:
      - config-server
      - authserver
      - eureka
    ports:
      - "8084:8084"
    command: ./wait-for-it.sh config-server:8888 -t 60 --
    command: java -Dspring.profiles.active=docker -jar /app.jar
  gateway:
    build: microservices-api-gateway/.
    working_dir: /
    links:
      - config-server
      - authserver
      - eureka
    ports:
      - "9000:9000"
    command: ./wait-for-it.sh config-server:8888 -t 60 --
    command: java -Dspring.profiles.active=docker -jar /app.jar